### PR TITLE
Libxml2 rebuild

### PR DESCRIPTION
**Pull request by SC426**
### Links

- [PKG-4629](https://anaconda.atlassian.net/browse/PKG-4629)

[PKG-4629]: https://anaconda.atlassian.net/browse/PKG-4629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by skupr-anaconda — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
An error on win64:
` C:\cygwin64\tmp\xmlXPathInitpg01tazt.c(1): fatal error C1083: Cannot open include file: 'libxml/xpath.h': No such file or directory`

I think it's related to this https://anaconda.slack.com/archives/C022V5KTUJF/p1721767786907799

**Comment by skupr-anaconda** [comment]
@danpetry win64 still fails:
`C:\b\abs_9airk1_mmq\croot\lxml_1721946551997\work\src\lxml\includes/etree_defs.h(12): fatal error C1083: Cannot open include file: 'libxml/xmlversion.h': No such file or directory`

`lxml` expects `libxml/xmlversion.h`, see  https://github.com/lxml/lxml/blob/bce5b10da0e5d9e7c49b318dd168656d34ab95a1/src/lxml/includes/etree_defs.h#L12

**Comment by skupr-anaconda** [comment]
@SC426 I enabled cython on win64 (before the package was built without cython).
However the issue of locating libxml2 persists. 
@danpetry This [PR](https://github.com/AnacondaRecipes/libxml2-feedstock/pull/17) is trying to solve it but it's not

**Review by JamesRobertsonGames — APPROVED** [review]

**Pull request merged**
